# Generated by Django 5.0.6 on 2024-05-17 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('serial_num', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=50)),
                ('quant', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
    ]
